### PR TITLE
Use curly braces initialization

### PR DESCRIPTION
**Pull request by bastiengrignon**

### CODE REVIEW

**Comment by polaco1782** [comment]
We're currently working on dash-next branch. this version is a legacy one.

**Comment by bastiengrignon** [comment]
Ok that's great thanks for the answer 🙂

**Comment by bastiengrignon** [comment]
@polaco1782 Do you want me to do it on the `dash-next` branch ? I'm sorry i didn't understand your previous comment

**Comment by polaco1782** [comment]
Hmm interesting, didn't know curly braces initialization is supported by embedded platforms.

**Comment by ayushsharma82** [comment]
We have updated to V3 logic. We will consider curly braces in that release. Thanks for your effort! This is certainly a new thing for us.

**Pull request closed without merging**
