### PR TITLE
Add library dependencies for PlatformIO.

### PR DESCRIPTION
**Pull request by ademuri**
Also configure Travis to build the examples using PlatformIO.

### CODE REVIEW

**Comment by ademuri** [comment]
The old travis build times out for me. I don't think you have that turned on for your project. If the PlatformIO build works, it may be worth removing it?

**Comment by ayushsharma82** [comment]
Never got Travis to run correctly for this repo.
Do you know how to script it?

**Comment by ademuri** [comment]
Yes, I modified `.travis.yml` so it works now: https://travis-ci.com/github/ademuri/ESP-DASH/jobs/348806915

**Comment by ayushsharma82** [comment]
@ademuri Looks like the script work! Thanks a lot. Travis has always been a pain in the neck to setup correctly.

What I noticed in Travis logs is that it builds every example in the directory. Can you modify the build script to just take one example of ESP8266 and ESP32? We just want to test if the library compiles or not.

**Comment by ayushsharma82** [comment]
Nevermind. Modified `build_platformio.sh` myself. It was fairly simple. Thanks! :)

**Pull request merged**
