### PR TITLE
Added pong response to ping, some changes

### PR DESCRIPTION
**Pull request by polaco1782**
Added response to ping. So the response can be verified in the dash if the ESP is online and responding.

### CODE REVIEW

**Comment by polaco1782** [comment]
I'm adding some functionality, like response time and last response from ESP. I have some connection issues, and sometimes my ESP connection drops out.

**Comment by ayushsharma82** [comment]
Thanks for your contributions @polaco1782 ! I will add a indicator on the dashboard if it doesn't receives a response from ESP back in 5 seconds. 

Currently, when the websocket connection disconnects (usually 10-15seconds), The logo will turn black and white and it will try to self-refresh the page..

**Comment by polaco1782** [comment]
> I guess, the `float` value will get truncated if we store it in `int` array of Number card?

In fact I did not stored it. I just thrown a 0 in there. I'm rewriting it to use a template, it will be much simpler.

**Comment by ayushsharma82** [comment]
Great. I will merge the pull requests when cosebase is ported to use `template`

**Comment by polaco1782** [comment]
> Great. I will merge the pull request when codebase is ported to use `template`

Nice, I've rewritten 70% of the code, sorry about that LOL, if you dont mind it. 
This was a very busy week, I'm currently reworking some internals. I might publish it this next week.

Now its even more simple to put a new board, like ESPDash.AddCard(TYPE_NUMBER_CARD, "card label", 50);

All types are now integers, and functions uses variadic templates.

**Comment by ayushsharma82** [comment]
I don't mind any changes if they are for a good reason.  Keep me posted and will templates offer a kind of `delete`  functionality? Where a user can delete a existing card? I never really used templates before, so this is going to be a new learning lesson for me 😃 .

**Comment by ayushsharma82** [comment]
@polaco1782  Any Update?

**Comment by polaco1782** [comment]
> @polaco1782 Any Update?

Yep, still working on it. Soon I'll commit.

**Comment by ayushsharma82** [comment]
@polaco1782  Okay

**Comment by ayushsharma82** [comment]
@polaco1782  That's some serious C++ Coding 😃  . I am astonished by your work.

**Comment by polaco1782** [comment]
> @polaco1782 That's some serious C++ Coding smiley . I am astonished by your work.

LOL, In fact my code isn't so good, It could be better. The STL used on the Arduino library is very limited, I hate that. Somehow they managed to create a C like with some C++ style thing.

There are some stuff missing, Slider, Button and Line/Gauge funcs needs some work. This was a very busy week, I've worked on it mostly this weekend. Maybe this week I finish all of it. :)

**Comment by ayushsharma82** [comment]
Great. I will add you as a collaborator on this repo. We can add the new code in a branch. Just don't change anything in `master` branch. We will merge it when the new version is working fine with everything.

**Comment by ayushsharma82** [comment]
@polaco1782  Sent you an Invite.

**Pull request closed without merging**
